### ISSUE TITLE
Segments almost lost with default retention rule

### ISSUE THREAD

**Issue by 8823Senior** [apache/druid#11222]
Segments almost lost with default retention rule (load forever) 

### Description

Using default retention rule (load forever)，But Segments almost lost.

Beginning, it is normal. but segments lost all suddenly.

I used docker-compose.yml below: 

```yaml
version: "2.2"

volumes:
  metadata_data: {}
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}


services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - metadata_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=FoolishPassword
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid
    ports:
      - '5432:5432'

  # Need 3.5 or later for container nodes
  zookeeper-druid:
    container_name: zookeeper-druid
    image: zookeeper:3.5
    environment:
      - ZOO_MY_ID=1

  coordinator:
    image: apache/druid:0.20.0
    container_name: coordinator
    volumes:
      - ./storage:/opt/data
      - coordinator_var:/opt/druid/var
    depends_on: 
      - zookeeper-druid
      - postgres
    ports:
      - "18081:8081"
    command:
      - coordinator
    env_file:
      - environment

  broker:
    image: apache/druid:0.20.0
    container_name: broker
    #network_mode: host
    volumes:
      - broker_var:/opt/druid/var
    depends_on: 
      - zookeeper-druid
      - postgres
      - coordinator
    ports:
      - "18082:8082"
    command:
      - broker
    env_file:
      - environment

  historical:
    image: apache/druid:0.20.0
    container_name: historical
    volumes:
      - ./storage:/opt/data
      - historical_var:/opt/druid/var
    depends_on: 
      - zookeeper-druid
      - postgres
      - coordinator
    ports:
      - "18083:8083"
    command:
      - historical
    env_file:
      - environment

  middlemanager:
    image: apache/druid:0.20.0
    container_name: middlemanager
    volumes:
      - ./storage:/opt/data
      - middle_var:/opt/druid/var
    depends_on: 
      - zookeeper-druid
      - postgres
      - coordinator
    ports:
      - "18091:8091"
    command:
      - middleManager
    env_file:
      - environment

  router:
    image: apache/druid:0.20.0
    container_name: router
    volumes:
      - router_var:/opt/druid/var
    depends_on:
      - zookeeper-druid
      - postgres
      - coordinator
    ports:
      - "18888:8888"
    command:
      - router
    env_file:
      - environment

```
