### ISSUE TITLE
add tier in helm chart 

### ISSUE THREAD

**Issue by jaegwonseo** [apache/druid#12249]
Currently, there is no tier setting for the historical node in the helm chart, do you have any plans to add a tier?

If you don't have a plan, I'll try adding it using range as shown below.

historical node statefulset.yaml
``` yaml
{{- range $key, $value := .Values.historical.tiers }}

historical statefulset helm chart

{{- end }}
```

values.yaml
```yaml
  tiers:
    default:
      replicaCount: 1
      env:
        druid_server_tier: xxxx
    cold:
      replicaCount: 1
      env:
        druid_server_tier: xxxx
```
