### ISSUE TITLE
Support helm chart to use a `Secret` resource to hide metadata storage db credentails.

### ISSUE THREAD

**Issue by imcheck** [apache/druid#14867]
### Motivation

I have tried to deploy druid using helm chart.
the helm chart doesn't support to inject environment variables related to metadata storage db credentials using `Secret` resource.
There's no way to inject the credentials unless using `ConfigMap` defined in values.yaml.

### Proposed changes

- Add a way to pull some configs like db credentials (`druid_metadata_storage_connector_user`, `druid_metadata_storage_connector_password`) to each process (broker, historical, ...) from `Secret` resource.
- It can be custom `Secret` user made outside this helm chart.

### Rationale

As I said on the above, it supports only to pull configs from `ConfigMap`.
It's hard to operate and manage `values.yaml` of this druid helm chart.

### Operational impact

It's just add changes. so, it keeps backward compatibility.

**Comment by jwitko** [comment]
@imcheck I was able to accomplish this by adding the following to the helm chart values:
```
  env:
    - name: druid_metadata_storage_connector_password
      valueFrom:
        secretKeyRef:
          name: druid-pg-app
          key: password
```
