### ISSUE TITLE
Druid Broker Heap memory increase until pod finally crash

### ISSUE THREAD

**Issue by yvesblt** [apache/druid#15069]
### Affected Version

Version 25.0.0

### Description
- Cluster size : 3 brokers with the following configuration:
```yaml
Limits:
  cpu:     18
  memory:  82Gi
Requests:
  cpu:      9
  memory:   41Gi

DRUID_MAXDIRECTMEMORYSIZE: 32000m
DRUID_XMS: 24576m
DRUID_XMX: 49152m
JAVA_OPTS: -XX:+UseG1GC
druid_broker_http_numConnections: 30
druid_processing_buffer_sizeBytes: 1073741824
druid_processing_numMergeBuffers: 16
druid_processing_numThreads: 16
druid_query_groupBy_maxOnDiskStorage: 5242880000
druid_server_http_numThreads: 40
druid_sql_enable: true
druid_sql_planner_metadataSegmentCacheEnable: true
druid_sql_planner_useApproximateTopN: false
```

Faulty behaviour: 
Our druid-cluster-broker pods are automatically restarted due to outOfmemory java-heap memory and the pod restart because of OOMKilled error 137.

We observe the same behaviour on all our broker pods: the JVM heap memory increase slowly and after several days it reaches the limit and crashes:
![image](https://github.com/apache/druid/assets/117368624/61ec962b-85b1-43c4-948d-3157a96ae910)

For some reason, the broker is not able to reduce its memory consumption. The number of GC cycles increase and each GC cycle become slower. It looks like it becomes less and less efficient :
![image](https://github.com/apache/druid/assets/117368624/299a3ed4-ff86-4756-ae51-4ed74a93f2d5)

When we connect to the pods, we see a high number of thread processes with the type `query-cancellat`. This number of `query-cancellat` is slowly increasing until the pods finally crashes.

Here's an example of a thread:
```shell
4631 druid     0:00 {query-cancellat} /usr/lib/jvm/jdk-11.0.17+8/bin/java --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED 
--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED 
-server -XX:+ExitOnOutOfMemoryError -Duser.timezone=UTC -Dfile.encoding=UTF-8 
-Djava.io.tmpdir=var/tmp -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager 
-Xmx49152m -Xms24576m -XX:MaxDirectMemorySize=32000m -XX:+UseG1GC -cp /tmp/conf/druid/cluster/_common:/tmp/conf/druid/cluster/query/broker:lib/*: 
org.apache.druid.cli.Main server broker
```

We set up a script that monitors the total number of thread and the number of thread of type `query-cancellat`in each broker pod:
![image](https://github.com/apache/druid/assets/117368624/3d755049-b56c-40fd-8f26-6c264b4ec542)

*Note: the graph is the result of all broker pods cumulated*

=> In grey, we see that the number of thread of type `query-cancellat` is continuously increasing.  
=> Meanwhile, the number of thread of all other types is remaining stable (orange)  

**We suspect that this increase of the number of `query-cancellat` thread inside the broker pods might be the root cause of the pod crashes. Does anyone know why it is not able to remove its `query-cancellat` threads ?**
