### ISSUE TITLE
druid fresh setup coordination & overlord db migration failing

### ISSUE THREAD

**Issue by btalukder-ea** [apache/druid#17870]
We were setting up druid version 32.0.1 .. using docker-compose 
but the coordinator service continuously restarting, when we check the error it is db migration fail.. 

DB is fresh db with no previous data. 

i think there is a race condition happening due to threads .. if we check the logs ..
1st it says creating table druid_tasks .. Table[druid_tasks] doesn't exist.

again one line is printed Adding column[type] to table[druid_tasks]. ..

but in the next moment it says task migration failed as  column "type" does not exist
then again in log, one error is printed, 
2025-04-03T13:28:38,248 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Creating table[druid_config]
2025-04-03T13:28:40,420 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Creating table[druid_audit]
2025-04-03T13:28:40,746 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - **Creating table[druid_tasks]**
2025-04-03T13:28:41,176 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Creating Index on Table [druid_tasks], sql: [CREATE INDEX idx_druid_tasks_active_created_date ON druid_tasks(active,created_date)] 
2025-04-03T13:28:41,677 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - **Adding column[type] to table[druid_tasks].**
2025-04-03T13:28:41,870 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Adding column[group_id] to table[druid_tasks].
2025-04-03T13:28:42,070 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - **Table[druid_tasks] doesn't exist.**
2025-04-03T13:28:42,264 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Creating table[druid_tasklocks]
2025-04-03T13:28:42,579 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Creating table[druid_dataSource]
2025-04-03T13:28:42,890 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Creating table[druid_pendingSegments]
2025-04-03T13:28:43,214 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Adding column[upgraded_from_segment_id] to table[druid_pendingSegments].
2025-04-03T13:28:43,406 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Adding column[task_allocator_id] to table[druid_pendingSegments].
2025-04-03T13:28:43,410 WARN [pool-20-thread-1] org.apache.druid.metadata.SQLMetadataStorageActionHandler - Task migration failed while reading entries from task table
org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: **column "type" does not exist**
  Position: 45 [statement:"SELECT * FROM druid_tasks WHERE id > '' AND type IS null ORDER BY id LIMIT 100", located:"SELECT * FROM druid_tasks WHERE id > '' AND type IS null ORDER BY id LIMIT 100", rewritten:"SELECT * FROM druid_tasks WHERE id > '' AND type IS null ORDER BY id LIMIT 100", arguments:{ positional:{}, named:{}, finder:[]}]

**Comment by btalukder-ea** [comment]
Could some one please look into this ... If required i can share the docker compose file

**Comment by gianm** [comment]
Could you please share some steps to reproduce this? Ideally a set of commands to run from either a fresh git checkout or a fresh download of some release artifact.

**Comment by btalukder-ea** [comment]
This is the docker-compose have used initially.. 
in environment file 
druid_extensions_loadList=["postgresql-metadata-storage"]
druid_metadata_storage_type=postgresql
druid_metadata_storage_connector_connectURI=jdbc:postgresql://<>connetor-uri?currentSchema=druid  #this schema it is populating
druid_metadata_storage_connector_user=username
druid_metadata_storage_connector_password=password
druid_metadata_postgres_dbTableSchema=druidt  #this does not work 

druid_storage_type=google
druid_google_bucket=druid_data
druid_zk_service_host=zookeeper
druid_zk_service_port=2181

```
version: "3.3"
volumes:
  metadata_data: {}
services:
  zookeeper:
    image: zookeeper:3.8
    restart: always
    ports:
      - "2181:2181"

  druid-coordinator:
    image: apache/druid:32.0.1
    restart: always
    environment:
      - DRUID_NODE_TYPE=coordinator
    command:
      - coordinator
    depends_on:
      - zookeeper
      - postgres        
    env_file:
      - environment        
    ports:
      - "8081:8081"
    volumes:
      - ./gcs-service-account.json:/opt/druid/conf/gcs-service-account.json

  druid-overlord:
    image: apache/druid:32.0.1
    restart: always
    env_file:
      - environment
    command:
      - overlord
    depends_on:
      - zookeeper
      - druid-coordinator
      - postgres        
    environment:
      - DRUID_NODE_TYPE=overlord
    ports:
      - "8090:8090"

  druid-broker:
    image: apache/druid:32.0.1
    restart: always
    command:
      - broker    
    depends_on:
      - zookeeper
      - postgres        
    env_file:
      - environment        
    environment:
      - DRUID_NODE_TYPE=broker
    ports:
      - "8082:8082"

  druid-historical:
    image: apache/druid:32.0.1
    restart: always
    command:
      - historical    
    depends_on:
      - zookeeper
      - postgres        
    env_file:
      - environment        
    environment:
      - DRUID_NODE_TYPE=historical
    ports:
      - "8083:8083"
    volumes:
      - ./gcs-service-account.json:/opt/druid/conf/gcs-service-account.json

  druid-middlemanager:
    image: apache/druid:32.0.1
    restart: always
    command:
      - middleManager    
    depends_on:
      - zookeeper
      - postgres        
    env_file:
      - environment        
    environment:
      - DRUID_NODE_TYPE=middleManager
    ports:
      - "8091:8091"

  druid-router:
    image: apache/druid:32.0.1
    env_file:
     - environment
    command:
      - router    
    restart: always
    depends_on:
      - zookeeper
      - postgres        
    environment:
      - DRUID_NODE_TYPE=router
    ports:
      - "8888:8888"
```
